### ISSUE TITLE
Bill of materials

### ISSUE THREAD

**Issue by asachs01** [adafruit/Kegomatic#5]
Hi Adafruit folks,

I've ordered a flow meter to try this project out. However, I can't seem to find the plastic barb fittings that work with the flow meter. Can you have a link on the article for making the project that would show where to buy the fittings?

**Comment by A9G-Data-Droid** [comment]
You're looking for a Barbed Tube Fitting Plastic Adapter. The flow meter has 1/2" NPS thread. So the adapter needs the 1/2" NPS female on one end and the barb size needs to match your tube. You can use any tube size but something 1/2in or smaller would make the most sense. If the tube were bigger then the flow meter would become a flow restrictor.

**Comment by asachs01** [comment]
@A9G-Data-Droid Yeah, I've been trying to find the fitting for ages, but it appears that no one makes them. In my case, I'm going from 1/2" --> 3/16" barb for the hose. It'd be super helpful to have a link to wherever they picked up the fitting. From what I can see on the tutorial, the tap they're using is a KegCo one (same as mine), so I'm assuming that they're using a fitting with a 3/16 barb too.

**Comment by asachs01** [comment]
https://forums.adafruit.com/viewtopic.php?f=8&t=93259 came up in another search. Why would that be so difficult to put in the article?

**Comment by ladyada** [comment]
if you can find and *verify* that an adapter from mcmaster,etc works - we'll add to the guide. just reply once you've verified. thanks!

**Comment by asachs01** [comment]
Hi @ladyada , thanks so much for hopping in! I've just found https://www.qcsupply.com/hose-barb-nylon-half-in-fpt-x-3-8.html, ordered, and will follow up w/ a verification once I have them.

**Comment by asachs01** [comment]
@ladyada apologies for the delay here. I've had success with [this barb fitting from US Plastics](https://www.usplastic.com/catalog/item.aspx?itemid=27795) and [unions](http://www.homedepot.com/p/Homewerks-Worldwide-1-2-in-PVC-Slip-x-Slip-Union-511-14-12-12H/204202875) from Home Depot. I'm also testing [this reducer bushing](https://www.usplastic.com/catalog/item.aspx?itemid=34916) to see if it might eliminate the need for the unions. But for sure, the union/barb combo is working.

**Comment by ladyada** [comment]
thanks added!! :)

**Comment by zawadzkip** [comment]
@asachs01 Is that barb fitting link still good? It looks like it's linking to a male NPT to barb adapter, when I believe a 1/2" female to 3/16" barbed fitting is needed?

**Comment by asachs01** [comment]
@zawadzkip yep, still good. I couldn't find anyone that would to the 1/2" female, so I ended up with these [unions](https://www.homedepot.com/p/Homewerks-Worldwide-1-2-in-PVC-Slip-x-Slip-Union-511-14-12-12H/204202875) instead. It adds another part to the mix, but works just fine.

**Comment by MatthijsvdVeer** [comment]
I used this [1/2" female to barbed fitting](https://www.usplastic.com/catalog/item.aspx?sku=62226). Please note I needed a 1/4" tube and not a 3/16" tube, but I don't think 3/16" is a must for this project. The female tubing fits the flow meter and [solenoid valves](https://www.adafruit.com/product/997) perfectly!
